list-pr-issue.sh
The script will list all of the open PRs in all of
the LSR repos, sorted from oldest create date to newest.
The script relies on the `hub` and `jq` commands.
=> add script to list open PRs in all LSR repos

README.md, sync-template.sh
Use the `hub` command to allow workflows that use your
local git user with your local git credentials e.g.
As a regular user, perform the usual
clone repo as origin
fork repo as myusername
make a change locally
push the change to my forked repo to a branch
submit a pull request from my forked repo to origin
This also makes the sync script both idempotent and able
to run incrementally.  That is, you can have the following
workflow:
make changes to template
sync the changes to repo R branch B
create a PR from branch B
make more changes to template
sync the changes to repo R branch B
push changes to branch B
This will update the existing PR with a new commit with the
additional changes on branch B
This PR also addresses a major limitation of the sync script -
it does not add new files to …
=> allow the use of the script with the hub command

README.md, sync-template.sh
My previous commit broke automated mode.  This fixes automated mode
and cleans up the code a bit.  There are two new cmdline flags:
`--workdir /path/to/dir` - instead of using the `$WORKDIR` env. var.,
pass it in with this flag.  This will automatically set `PRESERVE=true`
so as not to accidentally remove any directories under your workdir.
`--use-hub` - previously it would use `hub` automatically if found
in the `$PATH`.  Now, you must explicitly set `--use-hub` in order
to use `hub`.
=> fix automated mode

.travis.yml, tox.ini
add support for tox with pylint, pyunit, flake8, black, shellcheck
=> add support for tox with pylint, pyunit, flake8, black, shellcheck

lsr_role2collection.py
```
--src-path SRC_PATH   Path to the parent directory of the source role;
default to ${HOME}/linux-system-roles
```
=> lsr_role2collection.py - Fixing the help for "--src-path SRC_PATH".

ansible_role_parser.py
Fixing yamllint new-line-at-end-of-file.
error  no new line character at the end of file (new-line-at-end-of-file)
=> ansible_role_parser.py - appending '\n' to footer.

README.md, lsr_role2collection.py
For the preparation of the task, adding an option to specify the
tests path to copy.
```
--tests-dest-path TESTS_DEST_PATH
Path to parent of tests directory in which rolename directory
is created and test scripts are copied to the directory;
default to DEST_PATH/NAMESPACE/COLLECTION
```
=> RHELPLAN-42929 - Collections - script - add CI testing for collection

README.md, lsr_role2collection.py, tests/unit/test_lsr_role2collection.py
- Renaming the main function to role2collection.
- In the src path, allow a role is located in the directory other than "linux-system-roles".
- Adding --src-owner to specify github owner, e.g., "linux-system-roles".
=> Adjusting lsr_role2collection.py to the CI integration test env.

lsr_role2collection.py, tests/unit/test_lsr_role2collection.py
Import statement with a trailing comment like this
from ansible.module_utils.network_lsr import MyError  # noqa:E501
has to be converted to
from ansible_collections.fedora.system_roles.plugins.module_utils.network_lsr.__init__ import MyError  # noqa:E501
While examinig the path in module_utils, the comment had to be ingnored
then put back in the converted line.
=> lsr_role2collection.py - trailing comments were not properly handled

lsr_role2collection.py
Converting
roletoinclude: linux-system-roles.ROLENAME
to
roletoinclude: fedora.system_roles.ROLENAME
It is a hack to support tests/tests_include_vars_from_parent.yml
in certificate, kernel_settings, logging, nbde_client, nbde_server,
storage, and vpn.
A side note: Do we want to add tests_include_vars_from_parent.yml and its helper code to the newer roles, e.g., cockpit? (I don't see vars in firewall.)
=> lsr_role2collection.py - converting the value of roletoinclude

README.md, lsr_role2collection.py
Instead of checking the existence of the path with the role name, use meta/main.yml.
Plus, instead of using print, use the logging module to output the log messages.
And introduced an env var LSR_INFO to output the info level messages.
=> lsr_role2collection.py - the source role path does not have to end with the role name

lsr_role2collection.py
Check the link in the existing primary README.md file and add the link
only when it does not exist in the file.
=> lsr_role2collection.py - Avoid adding a duplicate link to README.md

lsr_role2collection.py, tests/unit/test_lsr_role2collection.py
If a test playbook contains a relative path such as
```
include_vars: relative_path/to/linux-system-roles.ROLENAME/file_or_dir
```
or
```
include_vars:
file|dir: relative_path/to/linux-system-roles.ROLENAME/file_or_dir
```
they need to be converted to the absolute path in the collection
format since the test playbook could be located at any place.
According to the include_vars doc, "If the path is relative and not
inside a role, it will be parsed relative to the playbook." To solve
the issue, the relative path is converted to the absolute path.
=> Support include_vars in the test playbooks

lsr_role2collection.py, tests/unit/test_lsr_role2collection.py
lsr_role2collection.py - In copying the roles tests dir to the collections
tests, by setting symlinks=False, it follows the links and copies the real
files and directories. Plus, when calling copy_tree_with_replace, set
"linux-system-roles.ROLENAME" to "ignoreme", which avoids copying the dir.
Removing unnecessary test case from test_lsr_role2collection.py
=> RHELPLAN-59755 - Collection - script - not include symlinks in the collection converted format

lsr_role2collection.py
It is based on the feature requirements:
https://issues.redhat.com/browse/RHELBU-298.
=> Changing the default collection name from "system_roles" to "linux_system_roles".

lsr_role2collection.py
In the rpm packaging process, the "linux-system-roles" part in FQRN
could be replaced with the package name, which is equivalent to the
src-owner value.
=> lsr_role2collections: Instead of hardcoded "linux-system-roles", use the src-owner value in FQRN.

lsr_role2collection.py
- Adding Vagrantfile and .yamllint.yaml to TOX list, which are not copied.
-  Adding .git* to the do-not-copy argument in copying tests dir to
drop .gitignore and .gitkeep.
- TOX files in each role are to be removed, but there were some
dead codes not making any effects. Replacing them with the
correct one.
- Selinux role has selinux-playbook.yml in the top level, which used
to be copied to playbooks/selinux, while other roles' examples are
copied to the docs/rolename dir. Adjusting selinux behavior to the
others.
- Adding README.html to DO_NOT_COPY list not to keep them in the
collection format.
=> lsr_role2collection: bug fixes found in the packaging

lsr_role2collection/collection_readme.md
Per discussion in the meeting, we'd better avoid using the word `collection` to reduce the confusion with `ansible collections`.
=> Replacing "a collection of roles" with "a set of roles" in lsr_role2collection/collection_readme.md

galaxy.yml
It is for fixing this failure in the packaging.
```
Traceback (most recent call last):
File "/usr/lib/rpm/ansible-generator", line 46, in <module>
main()
File "/usr/lib/rpm/ansible-generator", line 31, in main
for dep, req in info.get("dependencies", {}).items():
AttributeError: 'NoneType' object has no attribute 'items'
```
=> Commenting out empty dependencies in galaxy.yml

README.md, local-repo-dev-sync.sh
Useful for a linux-system-roles "administrator" role where you
want to have a local, up-to-date clone of all role repos, and
possibly run some sort of arbitrary command against all of them,
and a special purpose script like `sync-template.sh` isn't
suitable.  Also creates an upstream fork in your personal repo
if you don't already have one (so you can do feature work, submit
pull requests, etc.).
Requires `hub` and `jq`
=> ability to run a command in each repo

galaxy.yml
Note:
Collections that this collection requires to be installed for it to be
usable. The key of the dict is the collection label 'namespace.name'.
The value is a version range
L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification).
Multiple version range specifiers can be set and are separated by ','
dependencies: {}
=> Fixing the dependencies value type in galaxy.yml

lsr_role2collection.py
Symlinks in tests/roles are no longer valid once the role is converted
to the collections format. Function cleanup_symlinks is for cleaning
up such unnecessary symlinks, but there were leftovers. Fixed to clean
up thoroughly.
=> Bug fix in lsr_role2collection.py

md2html.sh
Usage: md2html.sh [-h] [[-l] md_file0 md_file1 ...]
If "-l" is set and if an option md file contains a link to
other md file in it, convert the link to html.
=> md2html.sh - adding an option -l

lsr_role2collection/.ansible-lint
galaxy-importer issues an error in importing the collection to Ansible galaxy:
```
WARNING: roles/ha_cluster/tasks/cluster-start-and-reload.yml:22:
[E503] Tasks that run when changed should likely be handlers
```
The error should be suppressed.
=> Adding a missing E503 to lsr_role2collection/.ansible-lint

lsr_role2collection.py
Since Automation Hub does not support the relative links in the doc,
the links would be broken in the GUI.
=> lsr_role2collection.py - Drop links from the Supported/Private role list

README.md, check_rpmspec_collection.sh
Description
- Verify rpm package count with various combination of ansible and
collection_artifact options.
- Check there is no README.html files in /usr/share/andible/collections.
Usage: ./check_rpmspec_collection.sh [ -h | --help ] | [ fedpkg | rhpkg [ branch_name ] ]
=> Adding check_rpmspec_collection.sh

README.md, lsr_role2collection.py, tests/unit/test_lsr_role2collection.py
mssql and some other roles need to change this:
```
- name: Run the role with default parameters
include_role:
name: linux-system-roles.mssql
```
to this:
```
- name: Run the role with default parameters
include_role:
name: microsoft.sql.server
```
python lsr_role2collection.py --role mssql --new-role server --namespace microsoft --collection sql
=> lsr_role2collection.py Introducing --new-role

README.md, lsr_role2collection.py, tests/unit/test_lsr_role2collection.py
Fixing [lsr_role2collection.py does not convert the legacy role path if the role is not the one to be converted. ](https://github.com/linux-system-roles/auto-maintenance/issues/65)
lsr_role2collection.py - introducing --extra-roles EXTRA_ROLES
The option takes comma separated extra roles to convert to collection.
This pr fixes the extra roles belonging to the same namespace.collection
as the role to be converted.
Example:
python  lsr_role2collection.py --role sap-hana-preconfigure \
--extra-roles "sap-base-settings,sap-preconfigure"
lsr_role2collection.py - introducing --extra-mapping EXTRA_MAPPING
Comma separated extra mapping - PRE:POST - to replace in the documentation
The option takes comma separated extra string mapping (format PRE:POST)
applied to the documentations. This option …
=> Fixing issue 65

lsr_role2collection/collection_readme.md, lsr_role2collection/collection_requirements.txt, release_collection.py
collection_requirements.txt - added
collection_readme.md - make dependencies programmable.
=> Improve dependencies in the packaging

lsr_role2collection.py
Note: Stop skipping the src role is the role to be converted to support the
case - the converted role name is changed and the original role name
appears in a doc file.
=> lsr_role2collection.py - adding an ability to convert "- ROLENAME" to "- FQCN" in the doc files such as README

lsr_role2collection.py
Some version fails to open a file containing non ascii characters, e.g., `author: First Škarvada <fskarvad@example.com>` as follows:
```
File "lsr_role2collection.py", line 281, in run
filepath, self.role_name, self.transformer_args
File "lsr_role2collection.py", line 136, in __init__
buf = open(filepath).read()
File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 32: ordinal not in range(128)
```
To avoid the failures, adding `encoding="utf-8"` to open.
=> lsr_role2collection.py - Adding encoding="utf-8" to open.

lsr_role2collection.py, lsr_roles2collections.sh
lsr_role2collection.py - drop python-six dependency
Instead of using "six.string_types" to check the task's module name,
use simple "str". If the script is run by python2 and the module name
is not ascii string, we may get unexpected results. But the chance
should be minimum.
=> lsr_role2collection.py - dropping python-six dependency

md2html.sh
pandoc should use `gfm` instead of `markdown_github`.  This makes the
internal links in the HTML work when converting the resulting
asciidoc to HTML.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1962976
=> pandoc - use gfm instead of markdown

collection_release.yml, galaxy.yml, lsr_role2collection.py, lsr_role2collection/runtime.yml
Ansible Galaxy collection import now requires that the collection
has a meta/runtime.yml.  This commit adds support for a default
meta/runtime.yml, and allows the user to override this when using
lsr_role2collection.
Other changes for 1.6.0 release
=> release 1.6.0; add meta/runtime.yml to collection

list-pr-statuses-ghapi.py, lsr_role2collection/runtime.yml
Bug 1989197 - drop support for Ansible 2.8
https://bugzilla.redhat.com/show_bug.cgi?id=1989197
=> Drop support for Ansible 2.8 by bumping the Ansible version to 2.9

README.md, release_collection.py
Command line examples:
```
python release_collection.py --force  --rpm ~/Downloads/linux-system-roles-1.8.2-1.fc36.noarch.rpm --no-update
python release_collection.py --force  --rpm ~/Downloads/rhel-system-roles-1.8.3-2.el9.noarch.rpm --no-update
```
The above examples generates the collection artifacts in ~/.ansible/collections:
```
fedora-linux_system_roles-1.8.2.tar.gz
redhat-rhel_system_roles-1.8.3.tar.gz
```
=> release_collection.py - adding an option "--rpm path/to/rpm"

lsr_role2collection/collection_bindep.txt, lsr_role2collection/collection_requirements.txt
The vpn role needs bindep `openssl` and `dnf`
We do not require `jmespath` or `netaddr` anymore
=> add bindeps; get rid of requirements.txt

release_collection.py
There is no way for a role to automatically require collections for
module/plugin dependencies.  Use the non-standard file
`meta/collection-requirements.yml` for this.  Note that
`meta/requirements.yml` is supposed to be a list of roles only, in
the format described at https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-multiple-files
If we find a `meta/requirements.yml` file, and it is not in `list`
format, assume it is an old one that has not yet been renamed to
`meta/collection-requirements.yml`, use it, and warn the user.
=> support collection-requirements.yml

README.md, lsr_role2collection.py
In addition to `linux-system-roles.rolename:fedora.linux_system_roles.rolename`,
`--extra-mapping` takes `fedora.linux_system_roles.rolename:redhat.rhel_system_roles.rolename`.
=> lsr_role2collection.py - add FQCN substitution to support "Roles Used by Other Roles"

README.md, bz-manage.sh
bz-manage helps with common system roles BZ admin tasks.
setitm, setdtm - set itm and dtm on BZs in a given itr and status (default is POST)
reset_dev_wb - check if the BZ has qa_ack+ and remove qa_ack? from the devel whiteboard field
- check if the BZ has Verified:Tested and remove the pre-verify? from the devel whiteboard field
get_commit_msg - get the summary of all BZ that are fixed by a dist-git commit (all BZ in POST state
which have release+) and format a suitable git commit message
get_cl - same as get_commit_msg, but for spec changelogs
new - create a new BZ for system roles
clone_check - see if all BZ in a given ITR (e.g. 8.7.0) have a corresponding clone
You must have the `bugzilla` command line client with appropriate token.
You must have the `jq` command line client.
=> add bz-manage.sh for managing system roles BZs

lsr_role2collection.py
Copy each role's `README.md` and `CHANGELOG.md` to the collections doc dir with renamed filename `README_ROLENAME.md` and `CHANGELOG_ROLENAME.md`, respectively.
=> lsr_role2collection.py - copy each role's README.md and CHANGELOG.md

lsr_role2collection.py
Bug fix introduced by the pr/167, in which collection conversion
fails in copying README and CHANGELOG files if docs dir does not
exist in advance.
=> lsr_role2collection.py - create docs dir if it does not exist

lsr_role2collection.py
The `missing_ok` argument to `Path.unlink` is not available
on python 3.6
=> allow lsr_role2collection.py to run on py36

README.md, bz-manage.sh
The function rpm_release will be used to generate the following
files:
* cl-md - the new entry to use for CHANGELOG.md
* cl-spec - the spec file %changelog section update
* git-commit-msg - the git commit message
The initial CHANGELOG.md is generated using spec_cl_to_cl_md.  Then
use rpm_release for subsequent releases.
=> add support for creating changelogs for rpm releases

README.md, release_collection.py
If we are using the commit hash to build the collection, there will
not be a version and a corresponding changelog.  In that case, use
the git commit titles and list them as Bug Fixes.
* This will inevitably be wrong - there will be New Features
and Other Changes listed erroneously - but there is no way to
know
* When there is an actual release with a version and a changelog,
some of the changelog information will be duplicated - the new
release will list some of the old changelog items again.
I think this is a minor problem to have as long as releases using
commit hashes are rare, and the changelog isn't really used in
Galaxy anyway.
Add support for `--use-commit-hash-role ROLENAME`.  For example,
if you want to do a collection release using the tag for every
role *except* sshd and …
=> use git commit subjects for changelog if no version

lsr_role2collection.py
Need an exceptional handling for `fedora.linux_system_roles` mapping.
@spetrosi, this fixed version could be used for your next build with the command line you shared with me. Let me double-check some observations...
The converted collection format contains the following `fedora.linux_system_roles` strings.
```
$ grep -R fedora.linux_system_roles
README.md:ansible-galaxy collection install fedora.linux_system_roles
README.md:After the installation, the roles are available as `fedora.linux_system_roles.<role_name>`.
README.md:/usr/share/ansible/collections/ansible_collections/fedora/linux_system_roles/roles/<role_name>/README.md
.collection/galaxy.yml:  "fedora.linux_system_roles": "*"
docs/CHANGELOG_server.md:- s/System Roles role/fedora.linux_system_roles.role/ to avoid ambiguity (#94) …
```
=> lsr_role2collection.py --extra-mapping bug fix

report-modules-plugins.py
Skip parsing the file vault-variables.yml - there won't be any
modules or plugins in this file, or jinja numeric operations -
the file should contain only vault encrypted variables.
=> skip vault-variables.yml - not sure how to configure for vault

README.md, check_jenkins.py
- wip
- add print_task_tests_info and print_task_console
=> check jenkins fixes

.github/workflows/publish_collection.yml
Add a GitHub workflow that once a day
- scans for new linux-system-roles updates
- build a collection from them
- publish the collection to Ansible Galaxy
- update tags
Signed-off-by: Jiří Kučera \<jkucera@redhat.com\>
=> Add publish_collection workflow

.github/workflows/publish_collection.yml, .github/workflows/tox.yml, release_collection.py
Use ansible-core instead of ansible - ansible-galaxy is provided by ansible-core
Ensure pypandoc dependencies are installed on ubuntu
Fix some shellcheck issues with shell usage in github action run
Use github action ::info and ::error
Do not add fedora.linux_system_roles as a dependency for itself - this causes a circular
dependency error in galaxy_importer
=> ensure pypandoc deps are installed; shellcheck issues; do not add fedora lsr as collection dep

.github/workflows/publish_collection.yml
Assumes
* systemroller token has permission to push
* systemroller token is in the `GH_PUSH_TOKEN` secret
* systemroller user is allowed to bypass branch protection rules
=> use systemroller account for push

README.md, collection_release.yml, release_collection.py
Added ad_integration and podman roles.
When you want to add a new role to the collection, add it in alphabetical order
to collection_release.yml with a `ref: null`.  The next time you use
release_collection.py to build the collection, it will update the ref with the
correct tag.  Also, the changelog will say
```
...
- ROLENAME - New Role
...
```
=> adding a new role - use ref: null; added ad_integration and podman

README.md, bz-manage.sh
The CHANGELOG.rst is now used for RHEL spec files instead of CHANGELOG.md.
bz-manage.sh `rpm_release` will now generate rST by default.
You can use `USE_MD=1` for Markdown.
=> Change bz-manage.sh rpm_release to generate rST for CHANGELOG

README.md, bz-manage.sh, release_collection.py
Use Markdown as the default format for CHANGELOG - generate
docs/CHANGELOG.md by default for collections.
=> make Markdown the default for CHANGELOG

lsr_role2collection/yamllint.yml, release_collection.py
role2collection is currently done using ruamel rt with a long line length,
because we can't ensure converted lines will be wrapped preserving
Jinja and ansible syntax.  This means we trigger a lot of warnings like
this when importing into Galaxy:
roles/file.yml:61: yaml line too long (187 > 160 characters)
the only thing we can do is suppress these
use both .ansible-lint and .yamllint.yml - depends on which version
of galaxy-importer/ansible-lint is being used
=> always skip ansible-lint line-length check

collection_release.yml, release_collection.py
Also, sort collection_release.yml according to this number, rather than alphabetically. Having the file sorted by sourcenum makes it easier to add new roles - otherwise it is difficult to figure out what is the last number used.
=> Number the roles according to their order in RPM spec

release_collection.py
When creating the changelog for the new collection version, the newly prepended changelog entry is saved as CURRENT_VER_CHANGELOG.md in addition to the update of the complete changelog. This is useful when creating a description for a release (because the release description should contain only what's new and not the complete changelog).
Optional, controlled by the `--save-current-changelog` argument.
=> Save the changelog entry for the current version

.github/workflows/publish_collection.yml
The release artifact will not contain the actual roles, only collection_release.yml that specifies their version, build helpers, and common files like changelog and metadata (galaxy.yml).
The main point of creating the GitHub release is to trigger Packit automation that will create a downstream (Fedora) RPM  build.
It will be also nice from a reproducibility point of view - it will provide a clear track record of which commit was used to build a particular collection version.
Other changes:
- Collection is published after commit and push. If we publish the collection first and the push then fails, we lose the sources that the collection was generated from. It is better to let the process fail before the collection gets published.
- Corrected one syntax error in GitHub action command …
=> Tag and release on GitHub when publishing new collection version

.packit.yaml
When there is a new release of this repo, Packit will fetch linux-system-roles.spec from the Rawhide branch in Fedora dist-git, update it (Source lines and %setup will be regenerated) and open a PR in Fedora Pagure. It will also upload new tarballs to lookaside and update sources.
The PR will be opened only against Rawhide for now, can be changed in dist_git_branches.
documentation:
https://packit.dev/docs/configuration/#propose_downstream
https://packit.dev/docs/fedora-releases-guide/
=> Configure Packit propose_downstream job

.packit.yaml
To build a new RPM after a PR in Pagure is merged.
https://packit.dev/docs/fedora-releases-guide/#koji-build-job
Note: I have not tested this job yet. Let's see...
=> Configure Packit Koji job

.packit.yaml
The koji and bodhi stuff are done in dist-git - see
https://src.fedoraproject.org/rpms/linux-system-roles/blob/rawhide/f/.packit.yaml
=> koji and bodhi stuff must be done in dist-git

.github/workflows/publish_collection.yml
The `create-release` action has been deprecated
https://github.com/actions/create-release
the highest rated replacement is
https://github.com/marketplace/actions/create-release
=> update create-release action

.github/dependabot.yml, .github/workflows/publish_collection.yml
packit does maintenence Tuesdays at 0000 UTC, so move the build job
one hour later to give packit plenty of time to recover
Add dependabot checking for github actions in this repo
=> move collection build job one hour later; add dependabot

release_collection.py
the .ansible-lint in each role now has dict and string valued
fields.  Make the code merge the dicts properly and skip
processing of string valued fields.
=> ansible-lint merge dicts as well as lists

README.md, lsr_fingerprint.py
`lsr_fingerprint` scans files in the `templates` dir under `./role["lsrrolename"]`, if the file contains a string `role["reponame"]:role["rolename"]`, replaces it with `system_role:role["lsrrolename"]`. Note: `role` is an entry of `roles` that is defined as an array of dictionaries in `lsr_fingerprint.py`.
For example, in metrics, `performancecopilot:ansible-pcp` is replaced with `system_role:metrics`; in sshd, `willshersystems:ansible-sshd` is with `system_role:sshd`.
=> Add lsr_fingerprint.py

README.md, manage_jenkins.py
manage is a better name since it allows you to cancel jobs as well
There were a few changes to the format of PR platform names and internal
directory names in the jenkins logs requiring changes to this tool.
=> fix: rename check_jenkins.py to manage_jenkins.py; fix recent issues

lsr_role2collection/runtime.yml
`2.11.0` is the minimum version supported by ansible-lint/ansible-test
This will not affect using ansible 2.9
=> fix requires_ansible version

lsr_role2collection.py
The old code would delete the old key using `pop` which would also
retrieve the value of the old key, then insert the new key with the
value at the old index.  This causes ruamel 0.17.23 and later to
crash with an "index out of range" error.  Instead, retrieve the value,
then insert the value with the new key at the old index, then finally
delete the old key.
=> ruamel now requires insertion of new key then deletion

.github/workflows/publish_collection.yml, release_collection.py
There is a bug in the current implementation.  The latest release
is https://github.com/linux-system-roles/auto-maintenance/commit/c3c7ab34502458e1b1bef9a29b4e1069d95ea27b
as you can see, both storage and rhc had new features, but only the storage
features were added to the changelog.  I tried to figure out how to use
the current code, but I gave up, and instead decided to use
python-markdown as the parser.  This simplified the code a great
deal.  I got rid of the obsoleted code and options.
=> use markdown parser for role README.md

manage-role-repos.sh
gh repo set-default --view now prints an empty string if unset,
so check for empty string and the "not set" message.
=> fix: gh repo set-default view prints empty string if unset

lsr_role2collection.py, report-modules-plugins.py
The podman role has test yml files that should not be processed
by lsr_role2collection or report-modules-plugins.  The lsr r2c
should skip processing any `files/` or `templates/` directories.
The `report-modules-plugins.py` should skip checking `files/`
files for plugins.
=> skip files directory to avoid yml file errors

README.md, bz-manage.sh
Now that all PRs in system roles follow the conventional commits format (see https://linux-system-roles.github.io/contribute.html#pr-description-format) we can automate updating doc texts in Bugzilla.
This PR expands the bz-manage.sh script with `update_doc_text`. To be run like `ITR=9.3.0 sh ./bz-manage.sh update_doc_text`.
When run, the script searches all PRs from the ITM and other filters provided and:
1.  If a BZ has required_doc_text flag set to `+` or `-`, the BZ is skipped. + indicates that the doc text has already been verified by a tech writer. - indicates that no release note is required. 
2. If a BZ has required_doc_text unset and GH PR set:
Automatically add doc text from PR description
3. If a BZ has required_doc_text? set and GitHub PR set:
If the existing doc_text is …
=> Add update_doc_text functionality to bz-manage.sh

lsr_role2collection/runtime.yml
Thanks to @myllynen for figuring how to specify support for
ansible 2.9 or later.
This solves ansible-lint issues such as
```
meta-runtime[unsupported-version] - requires_ansible key must contain a supported version, shown in the list above.
meta-runtime[invalid-version] - requires_ansible key must be a valid version identifier.
```
=> support ansible 2.9.10 or later

README.md, role-merge-prs.sh
Use `ci NUM` to add the `[citest]` comment to a PR
Use `t NUM` to show the detailed checks and test results - only shows
tests/checks which were not successful.
=> add citest to PRs; get detailed test results

role-make-version-changelog.sh
Keeping .README.html in each role's root dir would help to have a consistent .README.html in RPMs.
Keeping .README.html as a hidden file because it becomes outdated when new changes are made to README.md, and new release hasn't been created yet. The up-to-date README.html is stored in docs branch and is published to GitHub pages of each role as per https://github.com/linux-system-roles/.github/pull/41. 
See RHELPLAN-158622
=> As part of creating new release, get .README.html from docs branch

manage-role-repos.sh, role-make-version-changelog.sh
* Do not verify PR titles with commitlint when there are no PR
* Get docs:latest/README.html using gh api
* In manage-role-repos, ignore lsr-woke-action
=> Fix bugs in role-make-version-changelog

report-modules-plugins.py
Specifically, the certificate role stores a module that is used for tests only in tests/library
=> report-modules-plugins add local plugins from tests/library

callback_plugins/dump_packages.py, check-logs-for-packages.sh
- use invocation.module_args.name for packages
- exclude nested role packages from package lists
=> check logs no nested roles

lsr_role2collection.py, release_collection.py
Add `action_plugins` to the list of plugin directories to
process
add a `--keep` option for those cases where you need to
prepare	the collection directory ahead of time before
converting the roles
=> process action_plugins directory; add --keep option

lsr_role2collection.py
=> ansible-sshd now has a real directory tests/roles/ansible-sshd with role subdir links

callback_plugins/dump_packages.py
Some roles such as `cockpit` use the `yum` and `dnf` modules in
addition to the `package` module, so look for packages managed
by those modules.
=> dump_packages.py look for dnf and yum modules

lsr_role2collection.py, lsr_role2collection/runtime.yml, release_collection.py
Ensure .ansible-lint files written by collection conversion/creation
have the `---` doc start.
The meta/runtime.yml needs `requires_ansible: ">=2.13.0"` now.
NOTE that system roles still supports 2.9 and later, but gating
into Ansible repos now requires this.
=> fixes for latest ansible-lint - doc start, ansible 2.13.0

jira_playbooks/tasks/clone_and_link_issue.yml
For some reason Ansible casts them to `int`, so convert them back to
string when cloning.
=> cast itm and dtm to string when cloning

release_collection.py
release_collection was not ensuring that the code checked out to
use to build the collection matched the tag/hash specified.
The code will now ensure:
* if --no-update was used, just ensure the given cur_ref is
checked out, or main HEAD if cur_ref is None
* if cur_ref was set to a tag or commit hash, and there have been
no updates to the role code since that tag/hash, the tag/hash will
be checked out
* if there have been updates to the role code since the cur_ref
* if there is a new tag, check out that tag
* elif use_commit_hash is set, use main HEAD which is already checked
out
* else there have been role updates, but not yet tagged, and we
are not using the commit hash - ensure cur_ref is checked out
=> fix: release_collection should use code matching tag

report-modules-plugins.py
playbooks (tests are considered playbooks) may have local modules
and other plugins.  Process these first before processing the playbooks.
Then, process possible role directories under the playbook directory,
but do not treat it as a "real" role directory.
=> add local plugins first when processing playbook directories

lsr_role2collection/runtime.yml
ansible-lint 24.6.0 added a feature which allows you to specify
alternate versions to use instead of the one in meta/runtime.yml by
adding the config option `supported_ansible_also` to .ansible-lint
https://ansible.readthedocs.io/projects/lint/rules/meta-runtime/#configuration
Change this version to 2.14.0.  There will be follow up PRs to add
the option to all role .ansible-lint.
This should allow both ansible-lint and ansible-test to pass.
=> revert min ansible version back to 2.14.0

lsr_role2collection.py
The change in https://github.com/linux-system-roles/.github/pull/64 added `plans` directory with test plans to all roles. We do not want this directory to be in converted collections.
=> lsr_role2collection.py: Remove plans directory

get-github-stats.sh, manage-role-repos.sh, role-make-version-changelog.sh, role-manage-dependabot-alerts.sh, role-manage-prs.sh
Do not clone repo unless necessary.  This means you can use without
LSR_BASE_DIR.  It will create a tempdir for the cloned repo.
Clean up output a little for readability.
Do not prompt to release role unless AUTOSKIP=false.
Add new feature - AUTOSKIP_PR_TYPES - by default, if the only
changes to the role are `ci` related changes, the script will
skip that role.  If you really want to do a release of a role
which has only `ci` changes, set `AUTOSKIP_PR_TYPES=none`
=> improvements for role-make-version-changelog.sh

README-manage_issues.md, README.md, manage_issues.py
This version of manage_issues.py allows creation of multiple issues and
epics at the same time, and links the created issues to the created
epic.  It also allows creation of issues from github issues and PRs,
similar to manage-issues.sh.  There is still plenty of missing
functionality of manage-issues.sh.
=> manage_issues.py with ability create multiple issues and epics

callback_plugins/lsr_report_errors.py, check_logs.py
We will add this to all of our test runners - tox runqemu, testing farm, etc. - this will create a file `.json` corresponding to the log which will list the errors in the tasks in an easy to digest format - no more log parsing
=> callback plugin to collect task errors
