linux-system-roles/auto-maintenance

sync-template.sh
Add a `--local` switch - this allows you to copy files from your
local clone in order to e.g. test with `tox` locally.
Add support for the yamllint files.
=> add --local; add yamllint

lsr_role2collection.py
playbook files in the collection converted playbooks directory.
=> Converting "linux-system-roles." with "NAMESPACE.COLLECTION_NAME." in

lsr_role2collection.py, sync-template.sh, tests/unit/test_lsr_role2collection.py
- Merging ansible_role_parser.py into lsr_role2collection.py.
- Putting the main part of lsr_role2collection.py into main() function
and call it 'if __name__ == "__main__"'.
- Adjusting unittests to the refactored functions.
=> RHELPLAN-56489 - Collection - script - merge 2 python files into one

README.md, collection_release.yml, galaxy.yml, lsr_roles2collections.sh, release_collection.py
see the README.md - release_collection.py
=> Collection release scripts, data, docs

lsr_role2collection.py
Fixing a copying symlink bug.
Function lsr_copytree should keep symlinks if option symlinks is True;
copy its contents if option symlinks is False. There was a bug to check
symlink in lsr_copytree. Path.is_dir returns true for symlink dir and
it's treated as a directory.
=> RHELPLAN-59755 - Collection - script - not include symlinks in the collection converted format

lsr_role2collection.py
We only were using the Ansible parser to extract the task module
name and arguments.  We don't need this full parsing.  We only
need to look for a few module names, such as ones related to
roles, and ones related to role modules.  This is quite easily
done without the Ansible parser.
=> remove dependency on ansible, use only ruamel parser

README.md, lsr_role2collection.py, lsr_role2collection/collection_readme.md, lsr_roles2collections.sh
Usage:
python lsr_role2collection.py --role ROLENAME \
--readme /path/to/readme_src.txt
Generated readme
https://github.com/nhosoi/ansible_collections/tree/test/fedora/system_roles
=> RHELPLAN-63729 - collections - need README for collection for Ansible Galaxy

md2html.sh
Converts Markdown to HTML, useful for generating a readable local version of the READMEs.
=> Add script for building docs, from RHEL

galaxy_transform.py
Replaces collection namespace, name and version, using ruamel.yaml
=> Add a script to transform galaxy.yml

galaxy_transform.py
Description needs to be programmable.
=> RHELPLAN-69930 - Fix description field in galaxy.yml

check_rpmspec_collection.sh
Adjusting the expected behaviour based on the comment
https://src.fedoraproject.org/rpms/linux-system-roles/pull-request/4#comment-72412
=> Fixing check_rpmspec_collection.sh

md2html.sh
Bug 1943532 - Remove dependency on pandoc
https://bugzilla.redhat.com/show_bug.cgi?id=1943532
=> For .md to .adoc conversion, substitute pandoc with kramdoc

README.md, collection_release.yml, galaxy.yml, local-repo-dev-sync.sh, release_collection.py, roles-tag-and-release.sh, update_collection.py
Released fedora.linux_system_roles 1.3.0 to Galaxy
added roles-tag-and-release.sh
added update_collection.py
Improvements to local-repo-dev-sync.sh and release_collection.py
=> release collection 1.3.0

list-pr-statuses-ghapi.py
list-pr-statuses-ghapi.py will use the github api (ghapi)
You'll need to `pip install --user ghapi` to use it.
You'll need to grab your github token and supply it on the
command line or put it in ~/.config/hub (if you use the `hub`
command it will already be there).
=> initial version

lsr_role2collection/.ansible-lint
We fixed most of the issues in the code.
We still have a few issues in various places in the code.
=> update ansible-lint based on recent fixes

collection_release.yml, galaxy.yml
=> release 1.7.0

collection_release.yml, galaxy.yml
=> release 1.8.1

README.md, release_collection.py
Planning to use release_collection.py in the spec file with the --skip-git option.
=> release_collection.py - Add --skip-git option; Skip ansible-galaxy if it does not exist.

README.md, release_collection.py
Sorry, @richm. There was one more issue - galaxy-importer.
https://kojipkgs.fedoraproject.org//work/tasks/7272/77247272/build.log
=> release_collection.py - Add --skip-check option.

release_collection.py
Use only python packages available with el7
fix subprocess.run to work on python 3.6
add env to fix encoding problem - need to be able to pass
`LANG` and `LC_ALL` to subprocess
=> make release_collection.py work on el7

release_collection.py
add src_owner to release_collection.py pass through to lsr_role2collection
=> add src_owner to release_collection.py pass through to lsr_role2collection

report-modules-plugins.py
Add support for local filter_plugins
=> add support for role filter_plugins

update_vendored_collections/update_vendored_collections.py, update_vendored_collections/vendored_collections.yml
Please review for Python best practices
=> [WIP] Improve update_vendored_collections.py and prepare to run in container

.github/workflows/pull-request.yml, update_vendored_collections/update_vendored_collections.py
Do not add remote for github, print pushing message
Fix action's destination_branch
=> Fix auto creation of PRs

update_vendored_collections/vendored_collections.yml
Version 1.3.0 per current linux-system-roles.spec https://src.fedoraproject.org/rpms/linux-system-roles/blob/rawhide/f/linux-system-roles.spec#_234
=> Fix ansible.posix version to match linuxsystemroles.spec

update_vendored_collections/update_vendored_collections.py, update_vendored_collections/vendored_collections.yml
=> Fix the update-collections script - bump release in spec and build vendored_collections.yml correctly

roles-tag-and-release.sh
CHANGELOG_ONLY is set to true, roles-tag-and-release.sh allows to
work in the non-master/main branch and once CHANGELOG.md is edited,
it exits. You need to push the commit to the branch and open a pr
if necessary.
=> roles-tag-and-release.sh - add CHANGELOG_ONLY option

roles-tag-and-release.sh
When editing CHANGELOG.md, if the file starts with "# Changelog" or
"Changelog/n===...", keep them there.
=> roles-tag-and-release.sh - edit CHANGELOG.md

lsr_role2collection/COLLECTION_CHANGELOG.md
lsr_role2collection/COLLECTION_CHANGELOG.md
=> Add the initial collecion changelog file

release_collection.py
- If a version update is detected in a role, retrieve the changes
from the role's CHANGELOG.md and add them to COLLECTION_CHANGELOG.md.
- Copy COLLECTION_CHANGELOG.md to the converted collection's docs dir.
This pr depends upon https://github.com/linux-system-roles/auto-maintenance/pull/166 and https://github.com/linux-system-roles/auto-maintenance/pull/167.
@richm, this patch has not be tested as release_collection.py requires the version changes of one or more roles. Could you advice how you debugged the script? Maybe, I should use ci-testing for the purpose? Thanks! 
Note: this version has not supported when the ref is commit hash. Do we want to support a changelog item looks like this?
```
[COMMIT_HASH] - DATE
- change 0
- change 1
```
=> release_collection.py - Add CHANGELOG handling

README.md, lsr_role2collection.py
- bug fix: README needs to be copied to the doc dir after the extra-mapping..
- improve --extra-mapping to support mapping fedora.linux_system_roles to redhat.rhel_system_roles.
=> lsr-role2collection.py - improves collection mapping

lsr_role2collection.py, release_collection.py
- Fix a bug in lsr_role2collection.py
- Update release_collection.py to apply the changes made in lsr_role2collection.py
=> Convert fedora.linux_system_roles to NAMESPACE.COLLECTION

lsr_role2collection.py
Sorry, @richm. I'd like to add one more change to lsr_role2collection.py...
=> lsr_role2collection.py --extra-mapping - skip mapping to the same

lsr_role2collection.py
Look for FQCN for some ansible built-ins such as
ansible.builtin.include_role
ansible.builtin.import_role
ansible.builtin.include_vars
so that we can treat them the same way as the non-FQCN versions.
=> allow scanning of fqcn include_role, etc.

README.md, check_jenkins.py
=> check_jenkins.py - tool for checking baseos CI status

check_jenkins.py
Will now print the time that each stage of each test started - provision,
setup, test start, test end
=> more detail for print_task_tests_info

release_collection.py
@spetrosi, @richm, could you please take a look? Thanks!
=> release_collection.py - convert CHANGELOG.md into the reST format

release_collection.py
@richm, there was a logic bug in the Collection CHANGELOG.{md,rst} creation...
=> release_collection.py - need to convert existing CHANGELOG.md into the reST format as well

release_collection.py
Note: put execution-environment.yml in the collection top dir instead of the `meta` dir since the referred files, `requirements.yml`, `requirements.txt`, and `bindep.txt`, are in the collection top.
=> release_collection.py - Create execution-environment.yml in the collection

.github/workflows/publish_collection.yml, README.md
- Revert "test"
- Revert "disable branch protection before push"
=> revert changes to disable/enable branch protection rules for git push

README.md, release_collection.py
- add --skip-changelog
- add support for --extra-mapping argument
=> skip changelog

lsr_role2collection.py
The .ansible-lint file is also used for the collection, where
the paths are different.  Convert the paths in the
`exclude_paths` section of the role .ansible-lint from the
role into the collection format.
=> convert ansible-lint paths to collection format

report-modules-plugins.py
Tests can have dependencies declared in tests/collection-requirements.yml
in addition to the runtime dependencies in meta/collection-requirements.yml
=> handle tests/collection-requirements.yml

.packit.yaml
Also enable Packit Fedora builds on all branches.
See https://packit.dev/docs/fedora-releases-guide/#bodhi-update-job
=> Set up Packit automation for Bodhi updates 

release_collection.py
handle the case when there are changes to roles but none of them are
new features or bug fixes, which means things like
* test changes
* CI changes
* README
* other
In that case, just add a changelog like
```
- no user-visible changes
```
Also fix an issue with an extra newline after the new changelog
=> handle the case where there are no features, no bugs

check_jenkins.py, list-pr-statuses-ghapi.py
- add cancel_pr_tasks to cancel all tasks for the given PRs
- make this work with the latest baseos ci statuses
=> pr list with statuses

local-repo-dev-sync.sh
use CLONE_IT=false if you don't want to clone
This is useful if you want to perform an action that does not require a
local clone e.g.
`gh pr list -R linux-system-roles/$repo`
=> use CLONE_IT=false if you don't want to clone

release_collection.py, role-make-version-changelog.sh
release_collection.py
- Drop empty sections from the changelogs.
- Introduce an option --changelog-sections to support new titles.
```
--changelog-sections CHANGELOG_SECTIONS
List of the title of changelog sections;
Default to ['### New Features', '### Bug Fixes', '### Other Changes']
```
role-make-version-changelog.sh
- Instead of putting '- none', suggest to remove the entire section,
"### New Features", "### Bug Fixes", or "### Other Changes".
=> Update the changelog policy

lsr_fingerprint.py
change the fingerprints in the test code.  Allow duplicates
in the test code.
=> build: change fingerprints in tests too

README.md, role-make-version-changelog.sh
- install commitlint in ~/.local; fix conventional-changelog issue
- skip commit check if no tag; allow bad commits
- use correct regex to scan for features
- go directly to edit CHANGELOG.md if not skipped
=> role changelog install npm

role-make-version-changelog.sh
Developers write commits from a developer perspective and for developers, not for users. Sometimes there must be several commits in a single PR, and sometimes commits requre technical description. End users are not interested in technical details, they want to get information about how they benefit from code changes.
Hence, instead of collection commits into changelog, let's collect PR titile and description.
=> Collect PR descriptions instead of commmits into the changelog using API

README.md, check-fact-gather-results.sh
Check logs for fact gathering results.  See README for more info.
=> check logs for fact gathering results

check-fact-gather-results.sh
found some variables that were not marked local and could have been
leaking.
The only output by default now is error output - use `LOG_LEVEL`
to change the verbosity.
The script will now continue if it hits errors - be sure to capture
all of the output.
There was an issue with `rhc` skipping some fact gathering.
The script can now operate locally.  You can
download the beaker job xml to a local directory e.g.
```bash
mkdir -p /var/tmp/check
curl -s -L -o /var/tmp/check/beaker.xml http://beaker...../job.xml
./check-fact-gather-results.sh /var/tmp/check/beaker.xml
```
This will download all of the test run logs to /var/tmp/check if
they do not already exist.  If they do already exist, then the script
will use the local files.  This will greatly speed up processing if
you have to run the …
=> fix some issues found in testing

lsr_role2collection.py
When README.html file exists in repo, this file will be processed the same way as README.md.
=> Include README.html when converting to collection and some other fixes

check-logs-for-packages.sh
ostree - create/update roles files from logs
manage the roles-runtime.txt and roles-testing.txt files for roles that use other roles.
=> ostree - create/update roles files from logs

manage-role-repos.sh, role-make-version-changelog.sh
- do not fork empty repos
- do not release template role by default
- change wording to release instead of skip
=> manage role fixes

README.md, role-manage-prs.sh
Now shows review status - CHANGES_REQUESTED, COMMENTED, APPROVED, NO_REVIEWS
use `p NUM` to approve a PR
use `pm NUM` to approve and merge a PR
=> prs approve

sync-with-dist-git.sh
use e.g. `centpkg source` to download sources
from src branch
=> use source to get sources from src branch

check-logs-for-packages.sh
handle roles that have no Fedora, or do not have el8
=> handle roles that have no Fedora, or do not have el8

jira_playbooks/clone_and_link_issue_pb.yml, jira_playbooks/create_and_clone_issue_pb.yml, jira_playbooks/rpm_release_pb.yml, jira_playbooks/tasks/add_external_link.yml, jira_playbooks/tasks/clone_and_link_issue.yml, jira_playbooks/tasks/create_issue.yml, jira_playbooks/tasks/rpm_release.yml, jira_playbooks/tasks/update_issue.yml, manage-issues.sh
Fix formatting of rpm_release spec changelog entries, git commit
message entries
Add support for
- labels - add RHEL-System-Roles, and fixed_upstream if PR was merged
- itr, itm, and dtm
- docs_impact field
- dev_ack - set if there is a PR - qa_ack - will be set when cloned
Improve cloning - copy additional fields
=> several enhancements

jira_playbooks/tasks/create_issue.yml, manage-issues.sh
otherwise, doing
```
set_fact:
var: "Yes"
```
will convert `var` to a boolean.  We want it to be a string.
=> use ANSIBLE_JINJA2_NATIVE=1 for set_fact value: Yes

check-logs-for-packages.sh
Don't require a particular version of Fedora - just ensure that
there is at least 1 Fedora distro file.
Since there is no more upstream RedHat testing, create the RedHat
files from the CentOS files.
Add support for CentOS-10
=> no Fedora version; RedHat from CentOS; CentOS-10

README.md, get-github-stats.sh
=> add get-github-stats.sh

lsr_role2collection/collection_readme.md
https://access.redhat.com/articles/7068606 introduces a Certified Collections README Template that we want to comply with
I kept content that was in the readme before, and add some to fill in suggested sections.
I left out the `## Testing` section, it does not provide any helpful info for users imo, we describe how we test in our GitHub page https://linux-system-roles.github.io/.
=> docs: Update collection readme to comply with the template

role-make-version-changelog.sh
If you have to run the command again, it would be nice to skip roles that already have a version changelog PR in progress.  With this fix, you will get a message like this:
```bash
There is already a PR for version changelog:
#242 docs(changelog): version 1.3.7 [citest skip]
skipping tag/release for role certificate
```
=> skip changelog version if there is already a changelog version PR

collection_release.yml, galaxy.yml, lsr_role2collection/COLLECTION_CHANGELOG.md
=> version 1.90.0 - new role aide

role-manage-prs.sh
keep a list of prs to manage in the PR_LIST dict variable.  Do
not refresh the list, which also means we do not have to sleep.
This speeds up operation quite a bit.
=> keep a list of prs in a variable - do not refresh list every time

check_logs.py
Show data for testing farm jobs that are in progress - so you can see
how many tests have been run, which have passed/failed, and the
last test that was run.
=> show testing farm jobs in progress

check_logs.py
Look for and report unreachable errors - (task reports `UNREACHABLE!`, unreachable=1)
Add a new parameter `--beaker-job-list` which takes a whitespace delimited list
of beaker job IDs, so you can pass in a list from the `bkr` command e.g.
`--beaker-job-list "$(bkr job-list .... --format list)"`
Add extra fields to errors such as distro, arch, etc.
=> report unreachable errors; take a list of beaker jobs; add extra fields to errors

check_logs.py
=> show last line of beaker log

check_logs.py
=> get arch from ARCH_MANAGED_NODE; print job url
